# Site settings
title: Do words have (our) characters?
tag_text: Do words have (our) characters?
description: What words tell us about people
url: "http://127.0.0.1:4000"
baseurl: "/words-personalities"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md", "vendor/bundle"]
