# Site settings
title: Do words have (our) characters?
tag_text: Do words have (our) characters?
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "http://127.0.0.1:4000"
baseurl: "/_site"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
